
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "_/app/globals.css";
import Navbar from "./_Component/Navbar/Navbar";
import Footer from "./_Component/Footer/Footer";
import Infobar from "./_Component/Navbar/Infobar";
import { Toaster } from "_/components/ui/sonner"
import SessionProviderWrapper from "./_Component/SessionProviderWrapper/SessionProviderWrapper";
import CartContextProvider from "./_Context/CartContext";
import { getCart, getWishlist } from "_/Api/route.services";
import WishlistContextProvider from "./_Context/WishlistContext";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// const exo2 = Exo_2({
//   variable: "--font-exo2",
//   subsets: ["latin"],
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const res = await getCart();
  const wres = await getWishlist();
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`   antialiased`}
      >
        <WishlistContextProvider wres={wres}>

          <CartContextProvider res={res}>

            <SessionProviderWrapper >
              <Infobar />
              <Navbar />
              <div className="min-h-screen">

                {children}
              </div>
              <Toaster />

              <Footer />

            </SessionProviderWrapper>

          </CartContextProvider>
        </WishlistContextProvider>

      </body>
    </html>
  );
}
